---
version: 2.1

executors:
  golang:
    docker:
    - image: cimg/go:1.26

jobs:
  bump_version:
    executor: golang

    steps:
    - checkout
    - run: ./scripts/bump_version.sh

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "11 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
    - bump_version:
        context: org-context
