---
name: Check for new versions

on:
  schedule:
    - cron: "11 12 * * *"


permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.26.x
      - name: Check for new versions
        run: ./scripts/bump_version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
