name: Pre-submit tests
on:
  pull_request:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".github/workflows/ci.yml"

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  unit-tests:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make --always-make test-unit
