---
name: CI
on:
  push:
    branches: [master, 'release-*']
    tags: ['v*']
  pull_request:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - "*/Makefile.COMMON"
      - "*/base/*"
      - "*/main/*"
      - ".github/workflows/ci.yml"

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  unit-tests:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: make --always-make test-unit

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PROM_OSX_SDK_URL: ${{ secrets.PROM_OSX_SDK_URL }}
    strategy:
      matrix:
        go:
          - "1.25"
          - "1.26"
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go }}.x
      - run: make VARIANTS=base VERSION=${{ matrix.go }}
      - run: make VARIANTS=main VERSION=${{ matrix.go }}
      - run: docker images
      - run: ls -l docker-images
      - uses: prometheus/promci-artifacts/save@f9a587dbc0b2c78a0c54f8ad1cde71ea29a4b76f # v0.1.0
        with:
          directory: docker-images

  publish_master:
    name: Publish master branch artifacts
    runs-on: ubuntu-latest
    needs: [unit-tests, build]
    if: |
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main')
      ||
      (github.event_name == 'push' && github.event.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: prometheus/promci-artifacts/restore@f9a587dbc0b2c78a0c54f8ad1cde71ea29a4b76f # v0.1.0
      - name: Load images
        run: |
          for image in docker-images/* ; do
            docker image load --input "${image}"
          done
      - run: docker images
      - run: make tag
      - name: Login to ghcr.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: quay.io
          username: ${{ secrets.quay_io_login }}
          password: ${{ secrets.quay_io_password }}
      - run: make push
